### ISSUE TITLE
Few bugs in the page

### ISSUE THREAD

**Issue by sw-257** [SafaElmali/Hex-To-Rgb#11]
It should display an error for all the values greater than #ffffff , but it is working and showing  results for hex like #asafaz, #fgaraf, #asasas,  #ararar, etc.
Basically I'm able to put letters which come after 'f' at all the even places of the hex....like #azazaz won't show an error, but #zzazaz or #zzzzzz will.
The catch is eg. if I input #afafaf, it will show 175,175,175, but if I input #agafaf, it will show 10,175,175. It is just omitting the 2nd digit of the hex and showing only the value of 'a'. Similarly #bgafaf will give 11,175,175 and #cgafaf will give 12,175,175, and this is true for all the pairs, like #afaraf will give 175,10,175 and #ararar will give 10,10,10.
Secondly, I think you should limit the input to only 6 digits, as it is able to take 7 digits after # at present.

**Comment by SafaElmali** [comment]
Thank you for your interest! These days, I really don't have much time. But I will check it as soon as possible. Feel free to create a pull request :)

**Comment by sw-257** [comment]
Sure! I can try...
